---
title: "ML Final Project"
author: "Mason Bosley, Lou Miller, Max Wang"
date: "12/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(readr)
library(broom)
library(ggplot2)
library(rpart.plot)
library(tidymodels) 
tidymodels_prefer() # Resolves conflicts, prefers tidymodel functions
set.seed(123)

nba2021pergame <- read.csv("2021-PerGame-Player-Stats.csv")


nba2021_2022salaries <- read.csv("2021-2022-Player-Salaries.csv")
names(nba2021_2022salaries)[1] <- "Player"

nba2021pergame <- nba2021pergame %>% left_join(nba2021_2022salaries,by=c('Player')) %>%
  select(-AllStar)  %>%
  distinct(Player, .keep_all = TRUE) %>%
  filter(!is.na(Salary)) %>%
  na.omit()
head(nba2021pergame)
```

CROSS-VALIDATION
```{r}
nba_cv10 <- vfold_cv(nba2021pergame, v = 10)
```


REGRESSION
```{r}
nba2021pergame %>%
    ggplot(aes(x = PTS, y = Salary, color = factor(AllNBA))) + 
    geom_point(alpha = 0.2) + 
    geom_smooth(span = 0.8, se = FALSE) +
    theme_classic()
```

GAMS
```{r}
set.seed(123)

gam_spec <- 
  gen_additive_mod() %>%
  set_engine(engine = 'mgcv') %>%
  set_mode('regression') 

gam_mod <- fit(gam_spec,
    Salary ~ s(PTS) + s(AST) + s(WS) + s(Age) + s(DRB) + s(FT) + s(GS),
    data = nba2021pergame
)

par(mfrow=c(2,2))
gam_mod %>% pluck('fit') %>% mgcv::gam.check() 

gam_mod %>% pluck('fit') %>% summary()

gam_mod %>% pluck('fit') %>% plot( all.terms = TRUE, pages = 1)
```

```{r}
gam_mod %>% pluck('fit') %>% plot(all.terms = TRUE, pages = 1)
```


LASSO
```{r}
lm_lasso_spec_tune <- 
  linear_reg() %>%
  set_args(mixture = 1, penalty = tune()) %>% 
  set_engine(engine = 'glmnet') %>% 
  set_mode('regression')

full_rec <- recipe(Salary ~ G+ GS +FG +FGA + FG.+ MP + PTS +STL + BLK + Age + TOV + PF + ORB + DRB + TRB + AST + X3P + X3PA + X3P. + X2P + X2PA + FT + FTA + FT. + WS, data = nba2021pergame) %>%
  step_nzv(all_predictors()) %>% # removes variables with the same value
  step_normalize(all_numeric_predictors()) %>% 
  step_dummy(all_nominal_predictors())
lasso_wf_tune <- workflow() %>% 
  add_recipe(full_rec) %>% # recipe defined above
  add_model(lm_lasso_spec_tune) 

penalty_grid <- grid_regular(
  penalty(range = c(3, 7)), #log10 transformed 
  levels = 10)

nbatune_output <- tune_grid( # new function for tuning parameters
  lasso_wf_tune, # workflow
  resamples = nba_cv10, # cv folds
  metrics = metric_set(mae),
  grid = penalty_grid # penalty grid defined above
)

best_se_penalty <- select_by_one_std_err(nbatune_output, metric = 'mae', desc(penalty))
best_se_penalty

final_wf_se <- finalize_workflow(lasso_wf_tune, best_se_penalty) # incorporates penalty value to workflow

final_fit_se <- fit(final_wf_se, data = nba2021pergame)

tidy(final_fit_se) %>% filter(estimate!=0) %>% arrange(desc(abs(estimate)))

glmnet_output <- final_fit_se %>% extract_fit_parsnip() %>% pluck('fit') # get the original glmnet output

lambdas <- glmnet_output$lambda
coefs_lambdas <- 
  coefficients(glmnet_output, s = lambdas )  %>% 
  as.matrix() %>%  
  t() %>% 
  as.data.frame() %>% 
  mutate(lambda = lambdas ) %>% 
  select(lambda, everything(), -`(Intercept)`) %>% 
  pivot_longer(cols = -lambda, 
               names_to = "term", 
               values_to = "coef") %>%
  mutate(var = purrr::map_chr(stringr::str_split(term,"_"),~.[1]))

coefs_lambdas %>%
  ggplot(aes(x = lambda, y = coef, group = term, color = var)) +
  geom_line() +
  geom_vline(xintercept = best_se_penalty %>% pull(penalty), linetype = 'dashed') + 
  theme_classic() + 
  theme(legend.position = "bottom", legend.text=element_text(size=8)) +
  xlim(0,7700000) + ylim(-2500000,5000000)

glmnet_output <- final_fit_se %>% extract_fit_engine()
    
# Create a boolean matrix (predictors x lambdas) of variable exclusion
bool_predictor_exclude <- glmnet_output$beta==0

# Loop over each variable
var_imp <- sapply(seq_len(nrow(bool_predictor_exclude)), function(row) {
    this_coeff_path <- bool_predictor_exclude[row,]
    if(sum(this_coeff_path) == ncol(bool_predictor_exclude)){ return(0)}else{
    return(ncol(bool_predictor_exclude) - which.min(this_coeff_path) + 1)}
})

# Create a dataset of this information and sort
var_imp_data <- tibble(
    var_name = rownames(bool_predictor_exclude),
    var_imp = var_imp
)
var_imp_data %>% arrange(desc(var_imp))
```

```{r}
final_fit_se_output <- nba2021pergame %>%
  bind_cols(predict(final_fit_se, new_data = nba2021pergame)) %>%
    mutate(resid = Salary - .pred)

p1 <- ggplot(final_fit_se_output, aes(x = PTS, y = resid)) +
    geom_point() +
    geom_smooth() +
    geom_hline(yintercept = 0, color = "red") +
    theme_classic()

p1

 final_fit_se_output %>%
    mae(truth = Salary, estimate = .pred)
```


```{r}
nba2021per36 <- read.csv("Per36-Player.csv")


nba2021_2022salaries <- read.csv("2021-2022-Player-Salaries.csv")
names(nba2021_2022salaries)[1] <- "Player"

nba2021per36 <- nba2021per36 %>% left_join(nba2021_2022salaries,by=c('Player')) %>%
  select(-AllStar)  %>%
  distinct(Player, .keep_all = TRUE) %>%
  filter(!is.na(Salary)) %>%
  filter(MP > 300) %>%
  na.omit()
head(nba2021per36)
```

CLASSIFICATION
```{r}
tree_spec <- decision_tree() %>%
  set_engine(engine = 'rpart') %>%
  set_args(cost_complexity = tune(),  
           min_n = 2, 
           tree_depth = NULL) %>% 
  set_mode('classification') 

nba2021per36 <- nba2021per36 %>%
mutate(Pos = stringr::str_replace(stringr::str_sub(Pos,1,2),"-",""))

nba2021per36 <- nba2021per36 %>%
  mutate(Pos = as.factor(Pos))
  
data_fold <- vfold_cv(nba2021per36, v = 10)

data_rec <- recipe(Pos ~ FG +FGA + PTS +STL + BLK + Age + TOV + PF + ORB + DRB + AST + X3P + X3PA + X2P + X2PA + FT + FTA + FT., data = nba2021per36)

data_wf_tune <- workflow() %>%
  add_model(tree_spec) %>%
  add_recipe(data_rec)

param_grid <- grid_regular(cost_complexity(range = c(-5, -1)), levels = 10) 

tune_res <- tune_grid(
  data_wf_tune, 
  resamples = data_fold, 
  grid = param_grid, 
  metrics = metric_set(accuracy) #change this for regression trees
)

autoplot(tune_res) + theme_classic()

best_complexity <- select_by_one_std_err(tune_res, metric = 'accuracy', desc(cost_complexity))
best_complexity %>%
  pull(cost_complexity)
data_wf_final <- finalize_workflow(data_wf_tune, best_complexity)

pos_final_fit <- fit(data_wf_final, data = nba2021per36)


tune_res %>% 
  collect_metrics() %>%
  filter(cost_complexity == best_complexity %>% pull(cost_complexity))

tree_mod_lowcp <- fit(
    data_wf_tune %>%
        update_model(tree_spec %>% set_args(cost_complexity = .011)),
    data = nba2021per36
)

tree_mod_highcp <- fit(
    data_wf_tune %>%
        update_model(tree_spec %>% set_args(cost_complexity = .035)),
    data = nba2021per36
)

# Plot all 3 trees in a row
#par(mfrow = c(1,3))
tree_mod_lowcp %>% extract_fit_engine() %>% rpart.plot()
pos_final_fit %>% extract_fit_engine() %>% rpart.plot()
tree_mod_highcp %>% extract_fit_engine() %>% rpart.plot()
```




  Random Forest
``` {r}
library(vip)
conflicted::conflict_prefer("vi", "vip")

rf_spec <- rand_forest() %>%
  set_engine(engine = 'ranger') %>% 
  set_args(mtry = NULL, # size of random subset of variables; default is floor(sqrt(number of total predictors))
           trees = 1000, # Number of trees
           min_n = 2,
           probability = FALSE, # FALSE: get hard predictions (not needed for regression)
           importance = 'impurity') %>% # we'll come back to this at the end
  set_mode('classification') # change this for regression

# Recipe
data_rec <- recipe(Pos ~ FG +FGA + PTS +STL + BLK + Age + TOV + PF + ORB + DRB + AST + X3P + X3PA + X2P + X2PA + FT + FTA + FT., data = nba2021per36)

# Workflows
data_wf_mtry2 <- workflow() %>%
  add_model(rf_spec %>% set_args(mtry = 2)) %>%
  add_recipe(data_rec)

data_wf_mtry4 <- workflow() %>%
  add_model(rf_spec %>% set_args(mtry = 4)) %>%
  add_recipe(data_rec)

data_wf_mtry9 <- workflow() %>%
  add_model(rf_spec %>% set_args(mtry = 9)) %>%
  add_recipe(data_rec)

data_wf_mtry19 <- workflow() %>%
  add_model(rf_spec %>% set_args(mtry = 19)) %>%
  add_recipe(data_rec)
```

```{r}
# Fit Models
set.seed(123)
data_fit_mtry2 <- fit(data_wf_mtry2, data = nba2021per36)

set.seed(123)
data_fit_mtry4 <- fit(data_wf_mtry4, data = nba2021per36)

set.seed(123) 
data_fit_mtry9 <- fit(data_wf_mtry9, data = nba2021per36)

set.seed(123) 
data_fit_mtry19 <- fit(data_wf_mtry19, data = nba2021per36)
```

```{r}
# Custom Function to get OOB predictions, true observed outcomes and add a user-provided model label
rf_OOB_output <- function(fit_model, model_label, truth){
    tibble(
          .pred_class = fit_model %>% extract_fit_engine() %>% pluck('predictions'), #OOB predictions
          class = truth,
          label = model_label
      )
}

#check out the function output
rf_OOB_output(data_fit_mtry2,2, nba2021per36 %>% pull(Pos))
```


```{r}
# Evaluate OOB Metrics
rf_OOB_output <- function(fit_model, model_label, truth){
    tibble(
          .pred_class = fit_model %>% extract_fit_engine() %>% pluck('predictions'), #OOB predictions
          class = truth,
          label = model_label
      )
}

data_rf_OOB_output <- bind_rows(
    rf_OOB_output(data_fit_mtry2,2, nba2021per36 %>% pull(Pos)),
    rf_OOB_output(data_fit_mtry4,4, nba2021per36 %>% pull(Pos)),
    rf_OOB_output(data_fit_mtry9,9, nba2021per36 %>% pull(Pos)),
    rf_OOB_output(data_fit_mtry19,19, nba2021per36 %>% pull(Pos))
)


data_rf_OOB_output %>% 
    group_by(label) %>%
    accuracy(truth = class, estimate = .pred_class)
```

```{r}
rf_OOB_output(data_fit_mtry2,2, nba2021per36 %>% pull(Pos)) %>%
    conf_mat(truth = class, estimate= .pred_class)
rf_OOB_output(data_fit_mtry4,4, nba2021per36 %>% pull(Pos)) %>%
    conf_mat(truth = class, estimate= .pred_class)
rf_OOB_output(data_fit_mtry9,9, nba2021per36 %>% pull(Pos)) %>%
    conf_mat(truth = class, estimate= .pred_class)
rf_OOB_output(data_fit_mtry19,19, nba2021per36 %>% pull(Pos)) %>%
    conf_mat(truth = class, estimate= .pred_class)
```

CLUSTERING
```{r}
model_output <-data_fit_mtry4 %>% 
    extract_fit_engine() 

model_output %>% 
    vip(num_features = 30) + theme_classic() #based on impurity

model_output %>% vip::vi() %>% head()
model_output %>% vip::vi() %>% tail()
```

```{r}
model_output2 <- data_wf_mtry4 %>% 
  update_model(rf_spec %>% set_args(importance = "permutation")) %>% #based on permutation
  fit(data = nba2021per36) %>% 
    extract_fit_engine() 

model_output2 %>% 
    vip(num_features = 30) + theme_classic()


model_output2 %>% vip::vi() %>% head()
model_output2 %>% vip::vi() %>% tail()
```



```{r}
nba2021per36_sub <- nba2021per36 %>%
    select(STL, BLK, AST, TRB, FT., X3PA)

# Run k-means for k = centers = 3
set.seed(253)
kclust_k3 <- kmeans(nba2021per36_sub, centers = 3)

# Display the cluter assignments
kclust_k3$cluster


nba2021per36 <- nba2021per36 %>%
    mutate(kclust_3 = factor(kclust_k3$cluster))
```

```{r}
nba2021per36_sub <- nba2021per36 %>%
    select(STL, BLK, AST, TRB, FT., X3PA)

set.seed(253)
kclust_k3_scale <- kmeans(scale(nba2021per36_sub), centers = 3)
nba2021per36 <- nba2021per36 %>%
    mutate(kclust_3_scale = factor(kclust_k3_scale$cluster))

# Visualize the new cluster assignments
ggplot(nba2021per36, aes(x=`BLK`, y= `AST`, color=kclust_3_scale)) +
    geom_point()
```

```{r}
nba2021per36_sub <- nba2021per36 %>%
    select(STL, BLK, AST, TRB, FT., X3PA)

# Run k-means for k = centers = 3
set.seed(253)
kclust_k5 <- kmeans(nba2021per36_sub, centers = 5)

# Display the cluter assignments
kclust_k5$cluster


nba2021per36 <- nba2021per36 %>%
    mutate(kclust_5 = factor(kclust_k5$cluster))
```

```{r}
nba2021per36_sub <- nba2021per36 %>%
    select(STL, BLK, AST, TRB, FT., X3PA)

set.seed(253)
kclust_k5_scale <- kmeans(scale(nba2021per36_sub), centers = 5)
nba2021per36 <- nba2021per36 %>%
    mutate(kclust_5_scale = factor(kclust_k5_scale$cluster))

# Visualize the new cluster assignments
ggplot(nba2021per36, aes(x=`BLK`, y= `AST`, color=kclust_5_scale)) +
    geom_point()
```

```{r}
nba2021per36_sub <- nba2021per36 %>%
    select(STL, BLK, AST, TRB, FT., X3PA)

summary(nba2021per36_sub)
```

```{r}
set.seed(253)
kclust_k5_6vars <- kmeans(scale(nba2021per36_sub), centers = 5)

nba2021per36 <- nba2021per36 %>%
    mutate(kclust_5_6vars = factor(kclust_k5_6vars$cluster))


nba2021per36 %>%
  count(Pos,kclust_5_6vars)
```

```{r}
nba2021per36 %>%
    group_by(kclust_5_6vars) %>%
    summarize(across(c(STL, BLK, AST, TRB, FT., X3PA), mean))
```

```{r}
set.seed(253)
kclust_k3_6vars <- kmeans(scale(nba2021per36_sub), centers = 3)

nba2021per36 <- nba2021per36 %>%
    mutate(kclust_3_6vars = factor(kclust_k3_6vars$cluster))


nba2021per36 %>%
  count(Pos,kclust_3_6vars)
```

```{r}
nba2021per36 %>%
    group_by(kclust_3_6vars) %>%
    summarize(across(c(STL, BLK, AST, TRB, FT., X3PA), mean))
```


```{r}
# Data-specific function to cluster and calculate total within-cluster SS
nbaper36_cluster_ss <- function(k){
    # Perform clustering
    kclust <- kmeans(scale(nba2021per36_sub), centers = k)

    # Return the total within-cluster sum of squares
    return(kclust$tot.withinss)
}

tibble(
    k = 1:10,
    tot_wc_ss = purrr::map_dbl(1:10, nbaper36_cluster_ss)
) %>% 
    ggplot(aes(x = k, y = tot_wc_ss)) +
    geom_point() + 
    labs(x = "Number of clusters",y = 'Total within-cluster sum of squares') + 
    theme_classic()
```

